### ISSUE TITLE
May the code is easier to obtain?

### ISSUE THREAD

**Issue by eyuansu62** [zeeeyang/lexicalized_bitreelstm#3]

**Comment by zeeeyang** [comment]
Hi, thanks for your interest. The current training instructions are straightforward. May I ask which part you would expect to be easier. I'd like to offer further help.

**Comment by eyuansu62** [comment]
Thanks for your reply, because i run the compile.md and it failes, and i just want to read the code about the tree lstm part.

**Comment by zeeeyang** [comment]
You can check this file directly. https://github.com/zeeeyang/lexicalized_bitreelstm/blob/master/bidir%2Blex/root_model/cnn/bitreelstm.cc.
